src/objects/Badge_Earned__c.object
<CustomObject>
    <label>Badge Earned</label>
    <nameField>
        <displayFormat>B-{0}</displayFormat>
        <label>Badge Earned Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges Earned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Ducati_Badge__c</referenceTo>
        <relationshipLabel>Badges Earned</relationshipLabel>
        <relationshipName>Badges_Earned</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Badges Earned</relationshipLabel>
        <relationshipName>Badges_Earned</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Bike__c.object
<CustomObject>
    <label>Bike</label>
    <nameField>
        <label>Bike Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/objects/Customer_Bikes__c.object
<CustomObject>
    <label>Bike Owned</label>
    <nameField>
        <displayFormat>B-{0}</displayFormat>
        <label>Customer Bikes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bikes Owned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Bike__c</fullName>
        <label>Bike</label>
        <referenceTo>Bike__c</referenceTo>
        <relationshipLabel>Bikes Owned</relationshipLabel>
        <relationshipName>Bikes_Owned</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bikes Owned</relationshipLabel>
        <relationshipName>Bikes_Owned</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Ducati_Badge__c.object
<CustomObject>
    <label>Ducati Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ducati Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

force-app/main/default/classes/DucatiQueries.cls
public with sharing class DucatiQueries {

    @AuraEnabled
    public static list<Badge_Earned__c> getBadges(id customerId){
        return [select Badge__r.Image_Url__c, Badge__r.Name, Badge__r.Description__c, CreatedDate from Badge_Earned__c where Customer__c=:customerId order by CreatedDate DESC];
    }

    @AuraEnabled
    public static list<Customer_Bikes__c> getBikes(id customerId){
        return [select Bike__r.Image_Url__c, Bike__r.Name, Purchase_Date__c from Customer_Bikes__c where Customer__c=:customerId];
    }


}